## pybind11 array and buffer interface: A numpy user’s perspective

![pybind11-logo](images/pybind11_logo.png)

Dboy Liao

[GitHub](https://github.com/dboyliao)
[LinkedIn](https://www.linkedin.com/in/yin-chen-liao-69967188/)
[CakeResume](https://www.cakeresume.com/dboyliao)

In [9]:
import numpy as np

array = np.arange(16, dtype=np.int8).reshape(4, 4).copy()

```python
array.shape
```

```
array.strides
```

```python
array.data
```

```python
array.base
```

In [10]:
np.lib.stride_tricks

<module 'numpy.lib.stride_tricks' from '/Users/dboyliao/.pyenv/versions/3.8.1/lib/python3.8/site-packages/numpy/lib/stride_tricks.py'>

![array-2d](images/array_2d.drawio.svg)

In [11]:
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


![array-2d-flatten](images/array_2d_flatten.drawio.svg)

In [12]:
arr_flatten = array.ravel()
arr_flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int8)

In [23]:
print("1 == 4 * 0 + 1:", 1 == 4 * 0 + 1)
print("6 == 4 * 1 + 2:", 6 == 4 * 1 + 2)

1 == 4 * 0 + 1: True
6 == 4 * 1 + 2: True


In [20]:
arr_flatten[1] == array[0, 1]

True